CHANGELOG.md, Example/Kommunicate.xcodeproj/project.pbxproj, Example/Kommunicate.xcodeproj/xcshareddata/xcschemes/Kommunicate-Example.xcscheme, Example/Kommunicate/AppDelegate.swift, Example/Podfile.lock, Kommunicate.podspec, Kommunicate/Classes/KMPreChatFormViewController.swift, Kommunicate/Classes/Kommunicate.swift
Updated the Kommunicate framework to Swift 4.2 and did the same for the sample app. Also, removed some unused code from `Kommunicate` class.
All tests are passing in Xcode 10.0
=> [AL-2993] Update the sample app and framework to Swift 4.2

CHANGELOG.md, Example/Podfile.lock, Kommunicate.podspec, Kommunicate/Classes/Kommunicate.swift
- This PR will show conversation assignee details (name and image) in conversation list screen.
- It is based on https://github.com/AppLozic/ApplozicSwift/pull/157
- Tested on device.
=> [AL-3071] Show conversation assignee in conversation list screen

Example/Kommunicate.xcodeproj/project.pbxproj, Example/Kommunicate/AppDelegate.swift, Example/Kommunicate/Base.lproj/Main.storyboard, Example/Kommunicate/Info.plist, Example/Kommunicate/LoginViewController.swift, Example/Kommunicate/ViewController.swift
- Added login view which has three fields: user, email and password.
- Plus 'Login as Visitor' button to login without any user Id for trying the sample app.
- A screen to launch the chat and log out.
- Tested as a new and old user plus as a visitor. All are working fine in the sample app.
- To test the sample app pass application Id in the AppDelegate file and then run the app.
=> [AL-3254]Add Login and launch screen in sample app #trivial

CHANGELOG.md, Example/Podfile.lock, Kommunicate/Classes/KMConversationViewController.swift, Kommunicate/Classes/Kommunicate.swift
After this PR if the parent VC doesn't have a navigation controller then the Conversation VC will still be shown.
=> Handle the case when parent VC is not part of a nav controller

CHANGELOG.md, Kommunicate/Classes/KMConversationService.swift
We already pass the metadata while sending a message now it will also be passed in create group call.
Adding it here as it's only required in Kommunicate.
Tested it with a couple of examples, works fine. Tried different key-value combinations.
=> [AL-3393] Pass send message metadata in create group

Example/Podfile.lock, Kommunicate.podspec
This will fix an issue where the framework localization file was not part of the pod. Also, updated ApplozicSwift to 2.5.1 which contains some bug fixes.
Tried adding Kommunicate in a sample app and localization file is present.
=> [AL-3493] Podspec: Add strings file in resources

CHANGELOG.md, Example/Tests/KommunicateTests.swift, Kommunicate/Classes/KMConversationService.swift, Kommunicate/Classes/Kommunicate.swift
Added a new param `clientConversationId` in `createConversation` API which will accept the client Id that will be associated with this conversation and the same will be used to fetch the conversation.
Also, renamed(and deprecated) `createConversation` method in `KMConversationService` class.
Tried creating multiple conversations locally and fetched some, seems to be working fine.
=> [AL-3482]Accept clientConversationId in createConversation API

CHANGELOG.md, Example/Podfile.lock, Kommunicate.podspec, Kommunicate/Classes/Kommunicate.swift
Updated `ApplozicSwift` to 4.0.0 and moved the new conversation button in Conversation list's navigation bar to the end.
Tried creating new chat in the sample app, works fine.
=> Update ApplozicSwift and new chat button position

Example/Podfile.lock, Example/Tests/ConversationVCNavBarSnapshotTests.swift, Kommunicate/Assets/KMPreChatUserFormView.xib, Kommunicate/Classes/ConversationVCNavBar.swift, Kommunicate/Classes/FaqViewController.swift, Kommunicate/Classes/KMConversationViewController.swift
- Fixed warnings due to usage of deprecated APIs.
- Removed `navigationBarBackgroundColor` property from`ConversationVCNavBar` and changed delegate to `weak`. As we update the navigation bar colors in `setupAppearance(_ appearance: UINavigationBar)` using `UINavigationBar`.
- Updated ApplozicSwift and CocoaPods.
- All tests are passing.
=> Fix warnings and update dependencies #trivial

Gemfile, fastlane/Fastfile
It automates:
- Podspec version update based on release branch for ex: it will set `2.2.1` for branch: `release/2.2.1`.
- Create a version update commit and a new tag
- Run `pod lib lint`
- Push new release to trunk
- Create a release on GitHub
=> Add fastlane and create release lane #trivial

fastlane/Fastfile
- Added `version` and `releaseBranchName` params to pass this info to other lanes.
- Updated merge and fetch commands, to merge changes to `master` and `dev` before checkout.
- Tried this lane in `ApplozicSwift`, and it's working fine.
=> Fastlane: Add version and branch name params #trivial

Example/Podfile.lock, Example/Tests/PaymentTests.swift, Kommunicate.podspec, Kommunicate/Classes/ConversationDetail.swift, Kommunicate/Classes/KMConversationViewConfiguration.swift, Kommunicate/Classes/PricingPlan.swift
- Updated `ApplozicSwift` to 4.1.0, and used new AL constants.
- Disabled CSAT feature for now.
- All tests are passing.
=> Update dependencies and disable CSAT #trivial

CHANGELOG.md, Kommunicate/Classes/Extensions/KMConversationService+ConversationFeedback.swift, Kommunicate/Classes/Models/ConversationFeedback.swift, Kommunicate/Classes/Views/FeedbackRatingView.swift, Kommunicate/Classes/Views/RatingViewController.swift
- Changed ratings to `1, 5, 10` from `1, 2, 3`. This was done to match the new rating values in other platforms.
- Created a new model `ConversationFeedbackSubmissionResponse`, for feedback submission response. 
- These three cases are working fine in the sample app:
- When feedback is available.
- No feedback (but the state is closed).
- After feedback (from iOS) is submitted.
- Enable CSAT to try this feature:
```
Kommunicate.kmConversationViewConfiguration.isCSATOptionDisabled = false
```
=> [CM-122] Update Rating scale and submission response

CHANGELOG.md, Kommunicate/Classes/Extensions/KMUserDefaultHandler+Extension.swift, Kommunicate/Classes/Kommunicate.swift
- Added two new checks: When an empty App ID is passed, and when a new App ID is passed in the setup.
- In both the cases, `assertionFailure` has been added to stop the execution.
- In case of new App ID, they should delete the data through log out and log in again.
- Tested all three scenarios in the sample App.
=> [CM-120] Add sanity checks for empty and new App ID in the setup

CHANGELOG.md, Kommunicate/Assets/Localizable.strings, Kommunicate/Classes/Extensions/Style+Color.swift, Kommunicate/Classes/KMConversationViewController.swift, Kommunicate/Classes/Views/AwayMessageView.swift, Kommunicate/Classes/Views/ConversationClosedView.swift, Kommunicate/Classes/Views/RatingViewController.swift
If the status of a conversation is closed then the text field for the message will be disabled. And closed conversation view is shown at the top of this input field. This view will have the conversation restart option. If a user taps on this button then this view will be removed and the input field(ChatBar) will be shown again.
Tested in a variety of scenarios, such as when all attachment options are disabled, the away message is displayed and the rating view is also visible.
=> [CM-66] Add conversation restart feature

CHANGELOG.md, Example/Podfile.lock, Kommunicate.podspec, Kommunicate/Classes/Kommunicate.swift
Added a `typealias` for ApplozicSwift's `Style` type as it's required for changing style of different UI components. Now it can be used in the App without adding a separate import statement.
Tested by changing sent message text style in the sample app.
=> [CM-126] Add alias for Style type 📱

CHANGELOG.md, Example/Kommunicate.xcodeproj/project.pbxproj, Example/Kommunicate.xcodeproj/xcshareddata/xcschemes/Kommunicate-Example.xcscheme, Example/Kommunicate.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, Example/Podfile.lock, Kommunicate.podspec, Kommunicate/Classes/KMConversationViewConfiguration.swift
- Enabled CSAT, so now feedback option will be shown by default if a conversation has been resolved.
- Updated ApplozicSwift to 5.3.0.
- Changed sample app's build system to the new one.
- Tested: CSAT feature is working fine.
=> [CM-236] Enable CSAT and update dependencies

CHANGELOG.md, Example/Tests/KMConversationViewControllerTests.swift, Kommunicate/Classes/KMConversationListViewController.swift, Kommunicate/Classes/KMConversationViewController.swift, Kommunicate/Classes/Kommunicate.swift
* Fix the conversation was not switching
**Description:** 
In case the app is killed and open the conversation from notification,
Keep the app in the background and send the message for a different conversation, 
In that case, the conversation was showing old launched conversation not the new 
* Added observer for push notification this will be triggered based on the  `individualLaunch` 
* Tried with killed state and switch between the conversation by sending a message from a different conversation works fine
=> [CM-308] Conversation in not switch while we open conversation through notification 

CHANGELOG.md, Example/Podfile.lock, Kommunicate.podspec, Kommunicate/Classes/KMAppSettingsResponse.swift, Kommunicate/Classes/KMAppSettingsService.swift
- Fixed JSON parsing error in App settings response.
- Error comes when the primary color and 'powered by' key-values are missing.
- Now, they are optional. When the primary color is not present, app settings won't be changed.
- Updated ApplozicSwift to 5.7.0.
- Tested in both the cases: when the primary color is present and when it's not.
=> [CM-330] Fix JSON parsing error in app settings response

Example/Kommunicate_ExampleUITests/KommunicateCreateConversationAndSendMessagesTests.swift, Example/Podfile.lock, Kommunicate.podspec
- Updated ApplozicSwift to 5.7.1 as it contains some fixes.
- Tested by sending text messages, and played audio messages to verify audio play fix.
=> Update ApplozicSwift to 5.7.1 #trivial

Example/Podfile.lock, Kommunicate.podspec
- Updated `ApplozicSwift` dependency to the latest version 5.8.0.
- All tests are passing.
=> Update ApplozicSwift to 5.8.0 #trivial

Example/Podfile.lock, Kommunicate.podspec
- Updated `ApplozicSwift` dependency to the latest version 5.8.1.
- All tests are passing.
=> Update ApplozicSwift to 5.8.1 #trivial

CHANGELOG.md, Example/Kommunicate.xcodeproj/project.pbxproj, Example/Kommunicate/Base.lproj/Localizable.strings, Example/Podfile, Example/Podfile.lock, Kommunicate/Assets/Localizable.strings, Kommunicate/Classes/ConversationDetail.swift, Kommunicate/Classes/ConversationVCNavBar.swift, Kommunicate/Classes/Extensions/ALContact+Extension.swift, Kommunicate/Classes/Extensions/Style+Color.swift
- Added support for showing Agent's away status in the conversation detail.
- If the conversation assignee(agent) is in away mode and connected, then Agent's status will be shown as "Away".
- Earlier only online and offline status of the agent was shown. Now, there are three possibilities.
- If the user is not connected(online), then the away mode won't be checked.
- Dependent on [contact status changes in Applozic](https://github.com/AppLozic/Applozic-iOS-SDK-Dev/pull/769).
- I've pointed to [contact-status](https://github.com/AppLozic/Applozic-Chat-iOS-Framework/tree/contact-status) branch of the Applozic pod repo for now.
- Check screenshots in the description of this [Jira issue](https://applozic.atlassian.net/browse/CM-327).
=> [CM-327] Show agent's away status when an agent is in away mode

CHANGELOG.md, Kommunicate/Classes/Kommunicate.swift
- Fixed an issue where `clientConversationId` was not used if single thread is option enabled for this conversation or through dashboard.
- If `clientConversationId` is present then a new id for the unique conversation won't be created.
- Tested by creating a new conversation with a particular conversation ID when single thread option was enabled.
=> [CM-376] Use clientConversationId if present when single thread option is enabled

CHANGELOG.md, Kommunicate/Classes/KMConversation.swift, Kommunicate/Classes/Kommunicate.swift
- Fixed an issue where only dashboard settings for single thread conversation was used.
- Now, if `useLastConversation` property of `KMConversation` is true, then dashboard settings won't be used.
- Tested by enabling and disabling single thread option in the dashboard and locally.
=> [CM-395] Create a single thread if it's enabled for the conversation

CHANGELOG.md, Kommunicate/Classes/Kommunicate.swift
* Checked by creating a conversation with passing an agentIds and if only those agentIds are in the group 
* Tried creating a conversation with  withConversationAssignee and botIds and aganetIds and checked if the bot is replying or not
=> [CM-375 ] Fixed if agentIds are passed in the conversation the default agentId was added

.github/workflows/automerge.yml
- Added a GitHub action to merge a PR when it's ready.
- These checks will be performed before merging: `ready` label on PR, PR is approved and tests are successful.
- It will run on GitHub Actions.
- Merging this PR to master otherwise it won't run.
=> Add a workflow to merge PR on green #trivial

CHANGELOG.md, Kommunicate/Classes/KMAppSettingsResponse.swift, Kommunicate/Classes/KMAppUserDefaultHandler.swift, Kommunicate/Classes/KMBotService.swift, Kommunicate/Classes/KMConversationViewController.swift, Kommunicate/Classes/Kommunicate.swift
- Now, CSAT feature can be controlled from the Dashboard.
- Local setting is also present, which can be used to disable the CSAT feature.
- Rating screen will be shown only when it's enabled in the dashboard and not disabled locally.
- Tested in these scenarios: when it's enabled/disabled in the Dashboard and disabled/enabled locally.
=> [CM-410] Add support for enabling CSAT from the Dashboard

CHANGELOG.md, Example/Kommunicate.xcodeproj/project.pbxproj, Example/Podfile, Example/Podfile.lock, Kommunicate/Classes/KMConversationViewController.swift, Kommunicate/Classes/KMPushNotificationHelper.swift, Kommunicate/Classes/Kommunicate.swift
* This PR depends on PR first review will be required in this:  https://github.com/AppLozic/ApplozicSwift/tree/CM-451 
* Added the passing option for the text in `Kommunicate. showConversationWith(groupId ` this can be used for passing the prefilled text while launching the chat.
CODE 
```swift
Kommunicate.showConversationWith(groupId: "46383008", from: self, prefilledMessage: "Hi how are you doing") { (success) in
}
```
Testing: 
Tested it passing the message and see if it's showing in the chatbox or not.
Tested it by switching the conversation by taping notification see if that is cleared or not.
=> [CM-451] Add support for setting a prefilled message to send before launching a chat.

CHANGELOG.md, Example/Podfile.lock, Kommunicate/Classes/Kommunicate.swift, Kommunicate/Classes/Models/KMMessageBuilder.swift
- Added a 'send message' function that supports sending text and rich messages.
- Also, added a message builder that is used for creating an `KMMessage` object.
- Tested by sending a message and launching a chat.
=> [CM-474] Add send message API for sending text and rich messages

CHANGELOG.md, Dangerfile, Kommunicate/Classes/Kommunicate.swift
- Enabled document sharing in the default configuration.
- Also, updated the Jira URL in the `Dangerfile` to link to KM one.
=> [CM-519] Enable document sharing and update Jira URL📱 

CHANGELOG.md, Kommunicate/Classes/Kommunicate.swift
- Added an option in the launch conversation API to show conversation list on tap of the back button.
- By default it is disabled, so on tap of the back button launch screen will be shown not the conversation list.
- Tested by creating conversations after enabling and disabling this option. Verified if the correct screen is shown in both the modes. Launch code:
```swift
Kommunicate.createConversation() { result in
switch result {
case .success(let conversationId):
Kommunicate.showConversationWith(
groupId: conversationId,
from: self,
showListOnBack: true,
completionHandler: { success in
print("conversation was shown")
})
case .failure(let kmConversationError):
print("Failed to create a conversation: ", kmConversationError)
}
}
```
=> [CM-502] Add an option to launch a conversation with conversation list in the background

Kommunicate/Classes/Kommunicate.swift
Added the typealias for KMChatBarConfiguration 
The config can be used in KM like below to set the style 
```
// Text view's placeholder style
KMChatBarConfiguration.TextView.placeholder = KMStyle(font: .font(.normal(size: 16)), text: .red)
// Text view's text style
KMChatBarConfiguration.TextView.text = KMStyle(font: .font(.normal(size: 18)), text: .red)
```
Testing:
Tested the config works or not.
=> Add typealias for KMChatBarConfiguration #trivial  

CHANGELOG.md, Kommunicate/Classes/Extensions/KMConversationService+ConversationFeedback.swift, Kommunicate/Classes/Extensions/URLBuilder+ConversationFeedback.swift, Kommunicate/Classes/KMConversationViewController.swift, Kommunicate/Classes/Models/ConversationFeedback.swift
- Updated conversation feedback API to v2. Now, conversation feedback will be shown in the Dashboard as a feedback message is sent.
- Also, changed the request params and response parsing strategy.
- Tested by giving a feedback from the SDK, and it's shown like this in the dashboard:
=> [CM-557] Update conversation feedback API to v2 to show the feedback on dashboard

CHANGELOG.md, Kommunicate/Classes/Kommunicate.swift, Kommunicate/Classes/String+Extension.swift
- Added a check for empty user ID and whitespace/newline characters in the user ID.
- This will be validated when the `Kommunicate.registerUser(:)` method is called.
- An error will be printed and returned in case of a validation(user ID) failure.
- Tested with user IDs that contains spaces or newlines characters, confirmed that an error is thrown in this case.
=> [CM-545] Add a check for user ID and whitespace characters

CHANGELOG.md, Kommunicate/Classes/Extensions/Style+Color.swift, Kommunicate/Classes/KMAppSettingsService.swift, Kommunicate/Classes/Kommunicate.swift
- When the primary color is not present in the App settings, then the default primary color('5553B7') will be set.
- Also, changed the default text color of sent message and navigation tint color to `white`.
- This change was required to match the default style with other platforms like web plugin.
=> [CM-579] Set default primary color and sent message's text color

CHANGELOG.md, Kommunicate/Classes/KMConversation.swift, Kommunicate/Classes/KMConversationService.swift
- Added a team ID option in the `KMConversationBuilder` to assign a conversation to the team.
- This will be used when creating a new conversation.
- Tested by creating multiple new conversations with different team IDs.
=> [CM-581] Option to set the team ID when creating a new conversation

CHANGELOG.md, Kommunicate/Classes/KMPreChatFormViewController.swift, Kommunicate/Classes/String+Extension.swift
- Added an option in the pre-chat view to set the regular expression from outside to validate the phone number.
- Earlier we were using `NSDataDetector` to confirm if the number passed by the user is a valid phone number.
- Now, we'll only check it against the regex passed from outside, and when the regex is not present we'll use `NSDataDetector` to validate.
- This was requested by customers who want to set custom rules based on their country.
- Tested by changing the digit count in the regex like this:
```swift
preChatVC.phoneNumberRegexPattern = "\\d{8}"
```
=> [CM-635] Add an option to set the pre-chat view phone number regex

CHANGELOG.md, Example/Kommunicate/Base.lproj/Localizable.strings, Kommunicate/Assets/KMPreChatUserFormView.xib, Kommunicate/Assets/Localizable.strings, Kommunicate/Classes/KMPreChatFormViewController.swift, Kommunicate/Classes/Views/KMPreChatUserFormView.swift
- Added config options to show/hide certain fields in the pre-chat view.
- Also, added an option to set the mandatory fields, and if the user does not fill them, the error will be displayed.
- Moved `phoneNumberRegexPattern` to `PreChatConfiguration`.
- This was required to set the pre-chat view rules from outside.
Note: This PR is on top of #159 so make sure to merge that PR before this one.
=> [CM-633] Add config options to show certain fields in the pre-chat view

CHANGELOG.md, Example/Kommunicate.xcodeproj/project.pbxproj, Example/Podfile, Example/Podfile.lock, Kommunicate/Classes/KMConversationViewController.swift
- Now, away message's view will be updated on agent change. So, whenever a conversation is to an agent who is in away mode, then the away message will be shown.
- Earlier we were only checking the away status initially when the conversation is launched.
- Also, fixed an issue where the chat bar header view was visible after hiding away message due to `charLimitView` check in `showAwayMessage` method.
- Tested by changing conversation assignee to from bot to agent and vice versa. In case of bot there is no away message, so it will be hidden. Once a conversation is assigned to an agent, then the away message will be fetched from the server and shown to the user.
- Dependent on [this PR](https://github.com/AppLozic/ApplozicSwift/pull/384).
=> [TD-1611] Show/hide away message on agent change

CHANGELOG.md, Kommunicate/Classes/KMConversationViewController.swift, Kommunicate/Classes/MessageCharacterLimitManager.swift
- Fixed an issue where character limit was not shown when a conversation is assigned to a Dialogflow bot.
- Added an option to enable/disable the character limit check to activate/deactivate the check when bot is present.
- Tested by assigning a conversation to a Dialogflow bot and a normal agent.
=> [TD-1606] Fix character limit issue for Dialogflow bots

CHANGELOG.md, Example/Kommunicate.xcodeproj/project.pbxproj, Example/Podfile, Example/Podfile.lock, Kommunicate/Classes/ConversationDetail.swift, Kommunicate/Classes/KMConversationViewConfiguration.swift, Kommunicate/Classes/KMConversationViewController.swift
- Added a configuration option that prevents the user from sending a message when a conversation is assigned to a bot.
- It's disabled by default.
There are some cases where a user should just tap on rich message buttons when a conversation is assigned to a bot.
Tested by changing the value from AppDelegate:
`Kommunicate.kmConversationViewConfiguration.restrictMessageTypingWithBots = true`
Dependent on [this PR](https://github.com/AppLozic/ApplozicSwift/pull/388).
=> [TD-1667] Add an option to hide the message input when assigned to bot

CHANGELOG.md, Dangerfile, Kommunicate/Classes/Extensions/URLBuilder+Assignment.swift, Kommunicate/Classes/KMConversationService.swift, Kommunicate/Classes/Kommunicate.swift, Kommunicate/Classes/URLBuilder.swift
- Now, the conversation assignee can be updated in an existing conversation using `Kommunicate.createConversation()` method.
- This will work for existing conversations. For new conversation, create conversation method will create a new conversation.
Tested by updating the assignee in an existing conversation.
```swift
let kmConversation = KMConversationBuilder()
.withConversationAssignee("new-assignee")
.withClientConversationId("myfirstconversation")
.useLastConversation(false)
.build()
Kommunicate.createConversation(conversation: kmConversation) { result in
switch result {
case .success(let conversationId):
print("Conversation id: ",conversationId)
Kommunicate.showConversationWith(groupId: conversationId, from: self) {
shown in
print("Conversation shown")
}
case .failure(let …
```
=> [TD-1673] Update conversation assignee using createConversation method

CHANGELOG.md, Example/Kommunicate.xcodeproj/project.pbxproj, Example/Kommunicate/AppDelegate.swift, Example/Podfile, Example/Podfile.lock, Kommunicate/Classes/KMConversationViewController.swift
Added code to show feedback when a closed conversation was reopened and closed again.
After a resolved conversation is reopened, the feedback rating view did not show up after resolving a conversation.
This change was done to update the rating as per the latest conversation.
On the agent app, resolve an open conversation.
Deliver the feedback.
Restart the same conversation, and resolve it again to deliver the updated feedback for the newer conversation.
=> [TD-1718] Add feedback collection code after reopening a conversation

Sources/Kommunicate/Classes/KMConversationViewController.swift
Added a check for the type of the awayMessage variable
=> Away message status Flutter iOS crash #trivial

CHANGELOG.md, Example/Podfile.lock, Sources/Kommunicate/Classes/KMConversationViewController.swift
Reply Meta Data is not sending to the backend.
Reply Meta Data & DefaultChatContext MetaData dictionaries has values under same key “KM_CHAT_CONTEXT“ . When we try to merge both dictionaries, one is replaced by another.At the end we are losing one of the dictionary values.
I have tested locally.
=> [CM-759] Dynamic ReplyMeta Data is not reaching Webhook | iOS SDK

CHANGELOG.md, Example/Kommunicate/ViewController.swift, Sources/Kommunicate/Classes/Kommunicate.swift
There is no option to update the team id of a conversation after the creation.We have added a method to achieve it. The parameters of the method  are conversation object & team id, method will update the conversation with the new team id.
I have tested locally by calling the method the team updation happened successfully
Note :
I have changed some codes in view controller class to test this feature. Those changes will be removed once its tested.Please consider Kommunicate.swift  file changes for this PR.
=> [CM-780] Add support to update Team ID - KM SDK

CHANGELOG.md, Example/Kommunicate/AppDelegate.swift, Sources/Kommunicate/Classes/Kommunicate.swift
- Set S3 service as the default service for upload / download images.
A PR is filed already in KM Chat UI repo for this. [https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/pull/25](https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/pull/25)
Locally tested by pointing to the above PR branch.
=> [CM-824] Set s3 service as the default service for upload/download images | iOS SDK

CHANGELOG.md, Example/Podfile, Example/Podfile.lock, Sources/Kommunicate/Classes/Extensions/URLBuilder+ConversationFeedback.swift, Sources/Kommunicate/Classes/KMConversationViewController.swift
- Added oneTimeRating in ALK
- oneTimeRating = true -> Ask for feedback only once in a conversation
- oneTimeRating  = false -> Ask for feedback everytime the conversation is resolved.
- one more PR is there in KMChat UI repo: [PR]( https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/pull/33)
- Locally test by pointing to the KMChat UI branch
=> [CM-870] oneTimeRating feature | iOS SDK

CHANGELOG.md, Example/Kommunicate.xcodeproj/project.pbxproj, Example/Kommunicate/ViewController.swift, Example/Kommunicate_ExampleUITests/KommunicateCreateConversationAndSendMessagesTests.swift, Example/Podfile, Example/Podfile.lock
- Updated bitrise Workflow steps versions
- Updated Snapshot test pods
- replaced certificates,provisional certificates, team id, bundle ids with new account.
- added time delays before interruption alerts
=> [CM-956] Bitrise Test Case update & Use new account credentials

CHANGELOG.md, Sources/Kommunicate/Classes/Kommunicate.swift
- Empty Message is coming if handover option is added in welcome message.
- Extra message object is been added with only having metadata of `"KM_ASSIGN_TO" : "id"`.thatswhy empty message in showing on device side
- deviceside create new channel endpoint is older version when comparing to chat widget's
- added `KM_ASSIGN,KM_ASSIGN_TO,KM_ASSIGN_TEAM` flags to hidden category & removing messages having those flags same like `"hide": true`
- Web chat widget following the same way of handling
=> [CM-961] Blank message comes if handover option is added in welcome message

CHANGELOG.md, Example/Podfile, Example/Podfile.lock, Sources/Kommunicate/Classes/ConversationVCNavBar.swift, Sources/Kommunicate/Classes/Kommunicate.swift
- Added way to change the bot name via chat context of conversation
How to do it?
first update the chat context before creating the conversation like below
```
let messageInfo = ["bot_customization": ["id":"bot id to be customised","name":"custom name"]]
do {
try Kommunicate.defaultConfiguration.updateChatContext(with: messageInfo)
} catch {
print("Failed to update chat context: ", error)
}
```
then in conversation you can see your customised bot name.
=> [CM-1167] Added custom bot name feature

CHANGELOG.md, Example/Podfile, Example/Podfile.lock, Sources/Kommunicate/Classes/KMConversationViewController.swift, Sources/Kommunicate/Classes/Kommunicate.swift
- Observe events -> message, attachment message, agent leave
- Added chat log logic to sync zendesk and kommunicate messages
- When message event triggered, send message to /rest/ws/zendesk/message/send
- When attachment event triggered, send attachment to /rest/ws/zendesk/file/send
- When Agent ends chat from Zendesk, call Resolve conversation API and resolve the conversation.
- When "Restart conversation" is clicked, a new conversation is created to maintain a single chat thread.
- Handled Chat logs -> If the app is closed and opened again, it will sync the messages sent from Zendesk dashboard until session is live
=> [CM-1191] Observe Zendesk Agent Events from dashboard

CHANGELOG.md, Sources/Resources/Assets/Localizable.strings
- Fixed default localisation text issue for bottom start new conversation button. Customers can customize this on their project by using this flag `StartNewConversationButtonTitle`
=> Fixed default localisation text issue for start new conversation  button

CHANGELOG.md, Example/Podfile, Example/Podfile.lock, Sources/Kommunicate/Classes/Extensions/UIViewController+Extension.swift, Sources/Kommunicate/Classes/FaqViewController.swift, Sources/Kommunicate/Classes/KMConversationListViewController.swift
- Added customisation for back button on conversation list screen
- By default it will be arrow.You can customise the by following code
` Kommunicate.defaultConfiguration.enableBackArrowOnConversationListScreen = false/true
`
=> [CM-1302] Added customisation for back button on conversation list screen

Example/Podfile, Example/Podfile.lock, Sources/Kommunicate/Classes/Views/ConversationClosedView.swift
- Added customisation to visibility of restart conversation button on conversation screen. 
- This restart conversation button will be shown to end user once conversation gets resolved. By clicking this button user can restart the conversation.
- Now we can show/hide this button. By default it will be shown.
=> [CM-1308] Added customisation for restart conversation button

Sources/Kommunicate/Classes/Views/ConversationClosedView.swift
- hidden  `Have other queries?` label when restart conversation button is hidden
=> Restart conversation button customization bug fix

CHANGELOG.md, Sources/Kommunicate/Classes/Extensions/URLBuilder+Faq.swift, Sources/Kommunicate/Classes/Kommunicate.swift, Sources/Kommunicate/Classes/Utilities/KmConfigurationSetter.swift
- Added customisation flag to hide/show chat widget on helpcenter(FAQ) page
- Added this customisation for React Native (read settings from string)
- Linked PR: https://github.com/Kommunicate-io/KommunicateChatUI-iOS-SDK/pull/95
=> [CM-1355] Added Customisation to hide chat widget on helpcenter page

CHANGELOG.md, Sources/Kommunicate/Classes/KMConversationViewController.swift
Fixed converstation restart happening through message template even when the restart conversation button is disabled
- Add a `message_template.json` file inside `Examples for kommunicate` , dummy data is given below :
```
{
"templates": [{
"identifier":"1",
"text":"Main Menu",
"messageToSend": "button",
},{
"identifier":"2",
"text":"Human",
"messageToSend": "Handoff",
}
]
}
```
- Resolve the conversation from dashboard and enable the restart conversation button from `ALKConversation.swift` `hideRestartConversationButton` . Build the app and in this case the message templates should not be shown so that the user should not be able to restart the conversation when he is not allowed to restart it.
**Older scenario** ->
**Fixed scenario** ->
=> Fixed converstation restart happening through message template

CHANGELOG.md, Sources/Kommunicate/Classes/KMConversation.swift, Sources/Kommunicate/Classes/KMConversationService.swift
- Passed app name in the GROUP_CREATION_URL
- "GROUP_CREATION_URL": "iOS: <app_name>"
- if App Name is not available then AppID is passed
=> [CM-1535] Added Pass Group Creation URL 

CHANGELOG.md, Sources/Kommunicate/Classes/KMConversationListViewController.swift
Fixed agent status not updating in real time when the conversation is opened from conversations list
- Pull this branch
- Open X Code and build your app
- Agent online/offline status should be updating in real time when the conversation is opened from conversation list
=> Fixed agent online/offline status when conversation is opened from conversation list

CHANGELOG.md, Sources/Kommunicate/Classes/Views/RatingViewController.swift
- Added Bottom Anchor Constraint for the Submit Button.
- Increased the height of Comment Section from 80.0 to 120.0 . 
> ![Simulator Screenshot - iPhone SE (2nd generation) - 2023-08-03 at 09 24 31](https://github.com/Kommunicate-io/Kommunicate-iOS-SDK/assets/139110221/c4bd06cd-a0b1-42d5-b573-205b1e6eeb85)
> iPhone SE (2nd generation)
> ![Simulator Screenshot - SampleAppTesting - 2023-08-03 at 09 23 38](https://github.com/Kommunicate-io/Kommunicate-iOS-SDK/assets/139110221/8eb9c3b7-040b-4698-ad40-39e3d3d03a52)
> iPhone 14 Pro Max
> ![Simulator Screenshot - iPhone SE (2nd generation) - 2023-08-02 at 19 39 40](https://github.com/Kommunicate-io/Kommunicate-iOS-SDK/assets/139110221/96fc9dd7-b89b-4b4a-9d90-3b8ac74de8e6)
> iPhone SE (2nd generation)
> ![Simulator Screenshot - SampleAppTesting …
=> [CM-1571] Fixed the Submit button cutting issue in the rating bar and increased the height of comment section in rating bar.

CHANGELOG.md, Sources/Kommunicate/Classes/Views/RatingViewController.swift
- Removed the fixed constraint from the Submit Button. 
- iPhone 14 Pro Max
- iPhone SE 2nd Gen
=> [CM-1594] Fixed Keyboard overlapping on the Ratting Section

CHANGELOG.md, Sources/Kommunicate/Classes/KMConversationViewController.swift
- Hided the away message while the conversation is resolved.
=> [CM-1593] Fixed Away Message & Rating message overlapping

CHANGELOG.md, Sources/Kommunicate/Classes/KMConversationListViewController.swift, Sources/Kommunicate/Classes/KMConversationService.swift, Sources/Kommunicate/Classes/KMConversationViewController.swift
Passed `kmUserLocale` inside groupMetadata  and messageMetadata which is used to display welcome message in a specific language
1. Add welcome message in a specific language from [here](https://dashboard.kommunicate.io/settings/welcome-message).
2. Change your device language to the same language as that of welcome message.
3. Create a new conversation and verify that the welcome message is received for that specific language.
=> [CM-1391] Added kmUserLocale in groupMetadata and messageMetaData

CHANGELOG.md, Example/Podfile, Sources/Kommunicate/Classes/ConversationVCNavBar.swift
- DT_TOOLCHAIN_DIR was not able to evaluate LIBRARY_SEARCH_PATHS while building in XCode 15, hence updated the podfile to use TOOLCHAIN_DIR instead of DT_TOOLCHAIN_DIR. Check the issue [here.](https://github.com/CocoaPods/CocoaPods/issues/12012)
- ImageResource of KingFisher was conflicting with Xcode's GeneratedAssetSymbols.ImageResource, hence renamed the `ImageResource` as `Kingfisher.ImageResource`. Check the issue [here.](https://github.com/onevcat/Kingfisher/issues/2114)
I tried to build with Xcode 14 as well as XCode 15 beta 8 and the app was building successfully
=> [CM-1629] Added support for XCode 15

CHANGELOG.md, Sources/Kommunicate/Classes/KMAppSettingsResponse.swift, Sources/Kommunicate/Classes/KMAppSettingsService.swift
Changed hidePostCTA flag in iOS SDK.
- Add suggested reply to your bot from [here.](https://dashboard.kommunicate.io/settings/chat-widget-configuration#hide-rich-button)
- Disable suggested replies showing on click from [here.](https://dashboard.kommunicate.io/settings/chat-widget-configuration#hide-rich-button)
- Check whether hidePostCTA is working or not.
=> [CM-1635] Changed hidePostCTA flag in IOS SDK

CHANGELOG.md, Sources/Kommunicate/Classes/KMConversationService.swift
In the group metadata language update we were earlier using KMConfiguration.updatechatcontext. When quick reply is sent and its metadata is set, it was clashing with the updated chat context. Hence, a new method is created now to set group meta which will not affect other functionalities.
=> Language metadata fix

CHANGELOG.md, Sources/Kommunicate/Classes/KMConversationService.swift, Sources/Kommunicate/Classes/Kommunicate.swift
Added `"KM_PSEUDO_USER": "{\n  \"hidden\" : true,\n  \"pseudoName\" : true\n}"` inside KmUser's metadata for identification of pseudoname during registration.
=> [CM-1639] Added flag for identification of users with pseudo name

Sources/Kommunicate/Classes/Views/FeedbackRatingView.swift, Sources/Kommunicate/Classes/Views/RatingViewController.swift
- added colour to rating titles so that it will not change on dark mode.
- Before (Dark mode enabled)
- After (Dark mode enabled)
=> Fixed In dark mode rating icon names were not displaying.

CHANGELOG.md, Sources/Kommunicate/Classes/KMConversationListViewController.swift, Sources/Kommunicate/Classes/KMConversationViewController.swift, Sources/Kommunicate/Classes/Views/AwayMessageView.swift, Sources/Kommunicate/Classes/Views/FeedbackRatingView.swift, Sources/Kommunicate/Classes/Views/RatingViewController.swift
- Added dark mode support in noConversation Screen.
- Dynamic text color Support to away message text.
- Dynamic Support for rating view controller. (titleText, iconTitle, typingText)
- Disabled the forced  overrideUserInterfaceStyle to light.
- User need to enable dark mode from defaultConfiguration.isDarkModeEnabled. By default it is false.
- Figma link : https://www.figma.com/file/4cSLo3RwfBgZCZCeTtKzgP/iOS-UI%2FUX?type=design&node-id=0%3A1&mode=design&t=SIX3kccGAY0KhEtJ-1
https://github.com/Kommunicate-io/Kommunicate-iOS-SDK/assets/139110221/9b93fdce-582b-4f2d-b5bb-a65e546e417f
=> [CM-1449] Dark Mode Support part -1 | iOS SDK

Sources/Kommunicate/Classes/KMConversationListViewController.swift, Sources/Kommunicate/Classes/KMConversationViewConfiguration.swift, Sources/Kommunicate/Classes/Kommunicate.swift, Sources/Kommunicate/Classes/Views/AwayMessageView.swift, Sources/Kommunicate/Classes/Views/FeedbackRatingView.swift, Sources/Kommunicate/Classes/Views/RatingViewController.swift
- Added Customisation for dark color for  Conversation Background Color. `Kommunicate.defaultConfiguration.backgroundDarkColor`
- Added Customisation  for dark color for Conversation Screen Bottom Attachment bar Color. `Kommunicate.defaultConfiguration.chatBarAttachmentViewBackgroundColor`
- Added Customisation  for dark color Conversation Info Model added parameters with default values. `KMConversationInfoViewModel(infoContent: "This is your conversation info text", leadingImage: leading, trailingImage:trailing, backgroundColor: bg, contentColor: UIColor.white, contentFont:font,darkBackgroundColor: .white, contentDarkColor: .black)`
- Added Customisation for dark Color for FAQ Customisation. `Kommunicate.kmConversationViewConfiguration.faqDarkBackgroundColor` , …
=> [CM-1459] Dark Mode Support Part -2 

Sources/Kommunicate/Classes/KMConversationListViewController.swift
- Fixed the Start conversation button not hide issue in Conversation List Screen.
=> [CM-1699] hideBottomStartNewConversationButton is not hiding in empty conversation list 

Sources/Kommunicate/Classes/Kommunicate.swift
Passed string value for psuedoname flag while registering a visitor user
=> Passed string value to pseudoName flag while registering loginAsVisitor

Sources/Kommunicate/Classes/ConversationVCNavBar.swift
- Added the extended touch area for back button.
- added negative constraint to make back button more closer to the screen
=> [CM-1810] Increase the touch space for buttons in iOS SDK

CHANGELOG.md, Sources/Kommunicate/Classes/Kommunicate.swift
- Fixed sync call happening even when new message created at time == last sync time
- For the first time while opening zendesk it was not working because there was no handoff to agent as soon as the conversation is released from the bot
- Fixed chat transcript sending multiple times for zendesk handoff
=> [CM-1713] Zendesk (Zopim) integration optimisations

Sources/Kommunicate/Classes/KMConversationService.swift
- Whenever `createAndShowConversation` function called, update group metadata api is getting called
- So in backend it is stored as a message(message metadata update by user) and hence last message of the group is getting differed.
=> Removed unnecessay group metadata api on createconversation flow

Sources/Kommunicate/Classes/KMConversationViewController.swift
- Fixed  When button is linked with intent via button trigger from dashboard, local message metadata is not reaching the webhook
- When reply meta data  added along with button trigger, reply meta data is not reaching the webhook
=> [CM-1941] Added support for button trigger in reply metadata

Sources/Kommunicate/Classes/KMConversationService.swift
- Added the else block to share the response when there is no change in the assignee.
=> Fix for conversation not opening second time with same assignee

Sources/Kommunicate/Classes/ConversationVCNavBar.swift
- Fixed assignee image is not getting rendered on conversation when it is created with title.
- Instad placeholder image is getting rendered
=> [CM-1964] Fixed assignee image is not getting rendered on conversation when it is created with title

Sources/Kommunicate/Classes/ConversationVCNavBar.swift, Sources/Kommunicate/Classes/KMConversationViewConfiguration.swift
- Fixed assignee name getting cut in ui issue
- Optimised the code on ConversationVCNavBar file
(letters of the name is getting cut the bottom)
=> [CM-1234] Fixed name getting cut issue 

Example/Kommunicate/AppDelegate.swift
- Removed Color Customisation For Navigation Bar as it was making the text color on navigation bar black.
=> Removed SampleApp Navigation Bar Color Customisation

Sources/Kommunicate/PrivacyInfo.xcprivacy
- Added Privacy Manifest File in Kommunicate SDK.
- For User Defaults and Active Keyboards.
=> [CM-2012] ITMS-91053: Missing API declaration 

Sources/Kommunicate/Classes/KMPushNotificationHandler.swift
- Added Customisation to update color of in App Banner. Customisation is accessible for Background Color, Title Color, Content Color.
```
Kommunicate.defaultConfiguration.inAppBannerColor = UIColor.kmDynamicColor(light: .systemBrown, dark: .systemBlue)
Kommunicate.defaultConfiguration.inAppBannerTextColor = UIColor.kmDynamicColor(light: .white, dark: .black)
Kommunicate.defaultConfiguration.inAppBannerContentColor = UIColor.kmDynamicColor(light: .white, dark: .black)
Kommunicate.defaultConfiguration.inAppBannerRadius = 12
Kommunicate.defaultConfiguration.inAppBannerShadowRadius = 15
Kommunicate.defaultConfiguration.inAppBannerShadowOpacity = 0.5
Kommunicate.defaultConfiguration.inAppBannerShadowColor = UIColor.kmDynamicColor(light: .black, dark: .red)
``` …
=> [CM-1827] In App Notification Banner Colour Customization 

Sources/Kommunicate/Classes/KMPushNotificationHandler.swift
Reverts Kommunicate-io/Kommunicate-iOS-SDK#427
Reverted due to gesture recogniser not working.
=> Revert "[CM-1827] In App Notification Banner Colour Customization "

Sources/Kommunicate/Classes/KMConversationViewController.swift
- Added a check of last message if the last message is rating message then it will not ask for rating on every opening of the conversation.
https://github.com/user-attachments/assets/ca63669c-070b-4fda-ac18-1589a73d6ab6
https://github.com/user-attachments/assets/e4ec0aee-9133-4f14-a86e-4fe0251db0e2
=> [CM-1393] Rating asked everytime opening a resolved conversation | iOS SDK

Sources/Kommunicate/Classes/KMErrors.swift, Sources/Kommunicate/Classes/Kommunicate.swift
- Added a configuration to disable Jailbreak Detection.
- Added a check for checking Jail Break.
- Added a check for Frida.
- Cydia.app
- blackra1n.app
- FakeCarrier.app
- Icy.app
- IntelliScreen.app
- MxTube.app
- RockApp.app
- SBSettings.app
- WinterBoard.app
=> [CM-2165] Jailbreak Detection | iOS SDK & Agent App

Sources/Kommunicate/Classes/Kommunicate.swift
- Added a check for the isCSATEnabled for rateConversationMenuOption at time of register.
- In this the configuration for showing rateConversationMenuOption is true from code and from Dashboard the rating is disabled.
=> [CM-1844] rateConversationMenuOption should be not come when CSAT is Disabled | iOS SDK

Sources/Kommunicate/Classes/DataLoader.swift, Sources/Kommunicate/Classes/KMURLSessionPinning.swift
- Added SSL pinning in api.kommunicate.io
- If the SSL pining failed user will not get new response but old or saved response will be accessible. 
- Added the key for Prod and Test.
https://github.com/user-attachments/assets/e1128097-bd8d-4345-908f-36c844f18c66
=> [CM-2166] SSL Pinning | iOS SDK

Sources/Kommunicate/Classes/Extensions/KMConfiguration+Extension.swift, Sources/Kommunicate/Classes/KMURLSessionPinning.swift
- Added fix for SPM for SSL Pining. Created a check to use `KommunicateCore-Info` if in bundle the `KMExpectedPublicKeyHashBase64` is missing.
- Updated the User language update tag in metadata.
=> Fix for SPM and Update User Language | iOS SDK

Sources/Kommunicate/Classes/KMConversationViewController.swift
- Added a check for lastMessage Sent User ID and Conversation Assignee. If the value doesn't match the awayMessage UI will not get removed in New Message.
https://github.com/user-attachments/assets/24dcb9c1-9550-4bec-a5dd-c8be1bc80760
https://github.com/user-attachments/assets/216d5e33-985d-4a86-af1a-4ff90af50ac1
=> [CM-1814] If bot delay is set, Away message is not shown | iOS SDK

Example/Kommunicate.xcodeproj/project.pbxproj, Example/Kommunicate_ExampleUITests/KommunicateResolveAndAssignmentUITests.swift, Example/Kommunicate_ExampleUITests/TestCaseInfo.swift, Sources/Kommunicate/Classes/KMConversationViewController.swift, Sources/Kommunicate/Classes/Views/AwayMessageView.swift
- Added Test case for Restart Conversation, Assign to human, Away Message and Email Collection.
- Fixed Restart Conversation issue.
=> [CM-2314] 4 Automation in iOS SDK and API failure Fix for Github Actions

Sources/Kommunicate/Classes/KMConversationListViewController.swift
- Added the check to verify is Single Threaded conversation condition is enabled from dashboard on basis of that hiding the Bottom Start New Conversation button.
=> [CM-1707] Hide Start new conversation button on list screen when issinglethreaded is set to true
