- Example/Kommunicate/AppDelegate.swift
- Kommunicate/Classes/Kommunicate.swift
Tested. Merge it once ApplozicSwift dependency has been updated to a new version.
> [AL-2801]Add required changes for a new version of Applozic and set configuration

- Example/Podfile.lock
- Kommunicate.podspec
Updates ApplozicSwift's version to 1.0.0
> ApplozicSwift: Bump version to 1.0.0

- Example/Kommunicate/ViewController.swift
- Kommunicate/Classes/KMConversationService.swift
- Kommunicate/Classes/Kommunicate.swift
This will add support for passing multiple agent ids while creating a conversation.
> Support multiple agentIds in createConversation

- Example/Podfile.lock
- Kommunicate.podspec
Updated podspec and podfile.lock file to reflect the version change.
> Release 0.8.0 🚀

- Kommunicate/Classes/Kommunicate.swift
Hides start new chat button by default.
> [AL-2983]Hide start new chat button

- Example/Tests/KommunicateTests.swift
- Kommunicate/Classes/Kommunicate.swift
It's an abstraction on top of the methods present to create and show conversations.
Also, added relevant tests cases.
> [AL-3042]Add a new method to create and show conversations

- Kommunicate/Assets/KMPreChatUserFormView.xib
- Kommunicate/Classes/KMPreChatFormViewController.swift
- Kommunicate/Classes/KMPreChatUserFormView.swift
- Scrolls up the view when the keyboard is visible.
- Switch textfields using keyboard's next button.
- And some minor improvements.
> [AL-3068] PreChatView: Improve textfield switching and change scrolling functionality

- Example/Kommunicate.xcodeproj/project.pbxproj
- Example/Podfile.lock
- Example/Tests/PaymentTests.swift
- Kommunicate.podspec
- Kommunicate/Classes/KMConversationViewController.swift
- Kommunicate/Classes/PricingPlan.swift
It will be shown in the release build and when the user logs in.
It depends on [PR 117](https://github.com/AppLozic/ApplozicSwift/pull/117) so merge when ApplozicSwift gets released.
> [AL-3160]Show suspension screen in the free plan

- CHANGELOG.md
- Example/Podfile
- Example/Podfile.lock
- Kommunicate/Classes/DataLoader.swift
- Kommunicate/Classes/KMConversationService.swift
- Kommunicate/Classes/KMConversationViewController.swift
- Kommunicate/Classes/URLBuilder.swift
- Kommunicate/Classes/Views/AwayMessageView.swift
This will add support for showing away message in the chat view.
> [AL-2853]Fetch and show 'away message'

- CHANGELOG.md
- Example/Kommunicate/ViewController.swift
- Example/Podfile.lock
- Kommunicate/Classes/Extensions/Sequence+Extension.swift
- Kommunicate/Classes/Extensions/URLBuilder+AwayMessage.swift
- Kommunicate/Classes/Extensions/URLBuilder+DefaultAgent.swift
- Kommunicate/Classes/KMConversationService.swift
- Kommunicate/Classes/Kommunicate.swift
- Kommunicate/Classes/URLBuilder.swift
- Now when creating a conversation, a default agent will be fetched and added.
- Also, did some code clean up.
> [AL-3062]Fetch and add a default agent when creating a conversation

- CHANGELOG.md
- Kommunicate/Classes/KMConversationViewConfiguration.swift
- Kommunicate/Classes/KMConversationViewController.swift
Notification will be posted when a user launches and closes the conversation.
> [AL-3188]Send notification when conversation view is launched and closed

- CHANGELOG.md
- Example/Kommunicate.xcodeproj/project.pbxproj
- Example/Podfile.lock
- Kommunicate.podspec
- Bumped the version to 1.1.0
- Updated CocoaPods to v1.6.0
- Updated ApplozicSwift to 2.2.0
> Release 1.1.0 🚀

- Example/Kommunicate.xcodeproj/project.pbxproj
- Example/Tests/KMConversationViewControllerTests.swift
- Example/Tests/Mocks/ConversationDetailMock.swift
- Kommunicate/Classes/ConversationDetail.swift
- Kommunicate/Classes/ConversationVCNavBar.swift
- Kommunicate/Classes/KMConversationViewController.swift
This PR will fix 2 issues :: 
1. Bot was coming offline always.
2. Assignee details were inconsistent in conversationView.
> Fix issue where bot was coming offline #trivial

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
Also updated ApplozicSwift to 2.4.0.
> Release 1.3.0

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
Also, updated the dependencies.
> Release 1.4.0

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
> Release 1.4.1 🚀

- CHANGELOG.md
- Example/Kommunicate/AppDelegate.swift
- Example/Kommunicate/ViewController.swift
- Example/Podfile.lock
- Kommunicate.podspec
- Kommunicate/Classes/KMConversationViewController.swift
- Kommunicate/Classes/Kommunicate.swift
This PR will add support for updating assignee details in real-time.
> Update assignee details in real time

- Example/Podfile.lock
- Kommunicate.podspec
> Release 1.5.0 🚀

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Kommunicate/Classes/ConversationVCNavBar.swift
Updated the podspec version to 2.0.0. Also, updated the dependencies.
> Release 2.0.0

- Example/Podfile.lock
- Kommunicate.podspec
> Release 2.1.0

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- MIGRATING.md
Updated pod version to 2.3.0 and updated the dependencies.
> Release 2.3.0

- README.md
Updated iOS to 10.0+, Xcode to 11.0+ and Swift to 4.2+
> [Docs] Update min. version requirement #trivial

- CHANGELOG.md
- Example/Kommunicate.xcodeproj/project.pbxproj
- Example/Podfile.lock
- Kommunicate.podspec
- Kommunicate/Classes/Kommunicate.swift
- README.md
> Release 2.5.0

- Example/Tests/KommunicateTests.swift
- Kommunicate/Classes/DataLoader.swift
- Kommunicate/Classes/KMConversationService.swift
- Kommunicate/Classes/KMErrors.swift
- Kommunicate/Classes/Kommunicate.swift
- MIGRATING.md
Added check in title should not be empty if they have passed from outside
> Add empty check for Conversation Title #trivial 

- Kommunicate/Classes/Kommunicate.swift
Change the deprecated method to use the latest create conversation method
> Use the latest create conversation method #trivial 

- CHANGELOG.md
- Kommunicate/Classes/KMConversation.swift
- Kommunicate/Classes/KMConversationService.swift
They can set the conversation Assignee using km builder
> [CM-152]Add conversation Assignee setter method #trivial 

- CHANGELOG.md
- Example/Kommunicate/ViewController.swift
- Kommunicate/Classes/KMErrors.swift
- Kommunicate/Classes/Kommunicate.swift
- MIGRATING.md
* Added the logout method with completion before there was no completion for logout. 
it was causing the issue if the customer calls the logout method and login method at a time.
> [CM-178] Add logout method with completion

- CHANGELOG.md
- Kommunicate/Classes/KMConversationListViewController.swift
- Kommunicate/Classes/KMConversationViewController.swift
* App info API to get the package details after suspension screen is shown
> [CM-185] Added support for syncing package details when a suspension screen

- Kommunicate/Classes/KMConversationListViewController.swift
* Moved the UI launch method in DispatchQueue.main as this was used in bg thread
> Move method in DispatchQueue.main.async #trivial 

- CHANGELOG.md
- Example/Podfile
- Example/Podfile.lock
- Kommunicate.podspec
- Kommunicate/Classes/KMAppSettingsService.swift
- Kommunicate/Classes/Kommunicate.swift
* Update ApplozicSwift 5.6.0
* Tested by changing the color from Kommunicate dashboard [link](https://dashboard.kommunicate.io/)
> [CM-14] Apply chat widget customization theme based on server response

- Example/Kommunicate/AppDelegate.swift
- Example/Kommunicate/ViewController.swift
Added the default Navigation Bar Appearance configuration
> Navigation bar appearance #trivial 

- Example/Kommunicate/AppDelegate.swift
Keep the default color which comes from the Applozic Swift SDk and removed the white color
> Update to use the same default color which is Swift SDK#trivial 

- Example/Kommunicate.xcodeproj/project.pbxproj
- Example/Kommunicate_ExampleUITests/KommunicateCreateConversationAndSendMessagesTests.swift
- Example/Kommunicate_ExampleUITests/KommunicateLoginAsVisitorUITests.swift
- Example/Kommunicate_ExampleUITests/TestCaseInfo.swift
1. Login through Login as a visitor button
2. Checked FAQ button
> [CM-351]UI Test for Login as a visitor and for FAQ button #trivial

- Example/Podfile.lock
- Kommunicate.podspec
Tested the PR with Download attachment and sending messages and receiving
> Update ApplozicSwift to 5.8.2 #trivial 

- Example/Kommunicate.xcodeproj/project.pbxproj
- Example/Kommunicate_ExampleUITests/KommunicateCreateConversationAndSendMessagesTests.swift
- Example/Kommunicate_ExampleUITests/KommunicateLoginAsVisitorUITests.swift
- Example/Kommunicate_ExampleUITests/KommunicateRichMessageUITests.swift
- Example/Kommunicate_ExampleUITests/TestCaseInfo.swift
1. Added UI Test cases for Rich messages
2. Added check for logout in KommunicateLoginAsVisitorUITests.swift 
3. Remove logout check from KommunicateCreateConversationAndSendMessagesTests.swift
> [CM-345]UI test for Rich Messages

- Example/Kommunicate.xcodeproj/project.pbxproj
- Example/Podfile
- Example/Podfile.lock
- Kommunicate.podspec
- Updated `ApplozicSwift` to 5.9.0
- All unit tests are passing.
> Update ApplozicSwift to 5.9.0 #trivial

- Example/Podfile.lock
- Kommunicate.podspec
✅ Updated ApplozicSwift to 5.10.0. 
✅ Updated Podfile.lock.
> Update ApplozicSwift to 5.10.0 #trivial

- CHANGELOG.md
- Example/Podfile
- Example/Podfile.lock
- Kommunicate/Classes/KMConversationViewController.swift
* This PR will depend on the AL [PR](https://github.com/AppLozic/ApplozicSwift/pull/366)
* Added the support for changing the bot language  
Tested with bot language in KM works fine.
> [CM-356] Add support for language change rich message

- Example/Kommunicate.xcodeproj/project.pbxproj
- Example/Podfile
- Example/Podfile.lock
- Kommunicate.podspec
✅ Updated ApplozicSwift to 5.11.0. 
✅ Updated Podfile.lock.
> Update ApplozicSwift to 5.11.0 #trivial

- CHANGELOG.md
- Kommunicate/Classes/KMConversationListViewController.swift
- Kommunicate/Classes/KMConversationViewController.swift
- Kommunicate/Classes/KMPushNotificationHelper.swift
- Kommunicate/Classes/Kommunicate.swift
* Enabled the screen transition in all screens 
**Testing:** Tested the works fine after enabling transition animation
> [CM-507] Enable screen transition animations in all screens

- CHANGELOG.md
- Kommunicate/Classes/ConversationVCNavBar.swift
Fixed the issue where after changing the language from the device the back button. was showing wrong.
> [CM-526] Fix the back button was not showing correctly on language change

- Example/Kommunicate.xcodeproj/project.pbxproj
- Example/Podfile
- Example/Podfile.lock
- Kommunicate/Classes/KMConversationViewController.swift
- Kommunicate/Classes/KMPushNotificationHelper.swift
Override the push notification selector for handling it in KM Side.
And updated the init method for passing the flag to AL.
This PR is on top of https://github.com/AppLozic/ApplozicSwift/pull/369
> Update the methods for conversation switching fix  #trivial

- Example/Kommunicate.xcodeproj/project.pbxproj
- Example/Podfile
- Example/Podfile.lock
- Kommunicate.podspec
✅ Updated ApplozicSwift to 5.11.1. 
✅ Updated Podfile.lock.
> Update ApplozicSwift to 5.11.1 #trivial

- README.md
- Replaced old conversation gifs in the README with the new ones.
- These new gifs show rich message templates.
> Update iOS bot conversation gifs in README #trivial

- .github/PULL_REQUEST_TEMPLATE.md
Added a pull request template to help the PR creators fill necessary details.
> Add pull request template #trivial

- Sources/Kommunicate/Classes/KMConversationViewController.swift
- Sources/Kommunicate/Classes/KMPreChatFormViewController.swift
- Sources/Kommunicate/Classes/Views/KMPreChatUserFormView.swift
Fix for errors in release build v6.0.0
> Fix for errors in release build v6.0.0 #trivial

- CHANGELOG.md
- Example/Podfile.lock
- Sources/Kommunicate/Classes/KMConversationService.swift
Added code to update group metadata when creating a conversation.
> [TD-1700] Add code to update group metadata

- CHANGELOG.md
- Sources/Kommunicate/Classes/KMConversationService.swift
Fix for the error during launching a conversation after the second time
> [TD-1943] Fix for launch conversation error

- Sources/Kommunicate/Classes/KMAppSettingsResponse.swift
- Sources/Kommunicate/Classes/KMAppSettingsService.swift
Added hidePostCTAEnabled setting in app settings
> Add support for hiding rich message buttons

- CHANGELOG.md
- Sources/Kommunicate/Classes/DataLoader.swift
- Sources/Kommunicate/Classes/URLBuilder.swift
> [TD-1867] Update bot detail API

- CHANGELOG.md
- Sources/Kommunicate/Classes/KMConversationViewController.swift
- Sources/Kommunicate/Classes/Kommunicate.swift
Add support to sync messages on chat screen opening
> [TD-1731] Add support to sync messages on chat screen opening

- CHANGELOG.md
- Sources/Kommunicate/Classes/KMConversationService.swift
- Sources/Kommunicate/Classes/Kommunicate.swift
Added support to update team for existing conversation
> [TD-2099] Add support to update team for existing conversation

- CHANGELOG.md
- Example/Kommunicate/Base.lproj/Localizable.strings
- Sources/Kommunicate/Classes/KMConversationListViewController.swift
- Sources/Kommunicate/Classes/KMPreChatFormViewController.swift
- Sources/Kommunicate/Classes/Views/KMPreChatUserFormView.swift
- Sources/Resources/Assets/KMPreChatUserFormView.xib
Added a password field to PreChat Form View. Is set to hidden currently.
> [TD-2111] Add password field to PreChatView Form

- CHANGELOG.md
- Example/Kommunicate.xcodeproj/project.pbxproj
- Example/Podfile.lock
- Kommunicate.podspec
- Sources/Kommunicate/Classes/KMConversationService.swift
Update AppLozicSwift to v6.3.0
> Update ALS to v6.3.0

- Example/Kommunicate.xcodeproj/project.pbxproj
- Example/Podfile
- Example/Podfile.lock
- Kommunicate.podspec
Updated Applozic Swift to 6.4.0
> Update ALS to 6.4.0

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
Update Pods and SDK version to 6.3.1
> Release - 6.3.1

- CHANGELOG.md
- Sources/Kommunicate/Classes/Extensions/URLBuilder+ConversationFeedback.swift
Update API endpoints for feedback URL
> [CM-670] Update API endpoints

- CHANGELOG.md
- Example/Kommunicate.xcodeproj/project.pbxproj
- Example/Podfile.lock
- Kommunicate.podspec
- Sources/Kommunicate/Classes/CustomPreChatFormViewController.swift
- Sources/Kommunicate/Classes/KMConversationViewController.swift
- Sources/Kommunicate/Classes/Kommunicate.swift
- Fixed warnings that are coming bitrise build
- removed changes in Kommunicate.podsspec
> Fix for warning

- CHANGELOG.md
- Example/Podfile
- Example/Podfile.lock
- Sources/Kommunicate/Classes/KMConversationListViewController.swift
Added listener callback to get Away/Online(APPLOZIC_25) status change in  realtime
Locally tested by using the callback
> [CM-758] Realtime user Away Online status update

- CHANGELOG.md
- Example/Kommunicate.xcodeproj/project.pbxproj
- Example/Podfile
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Sources/Kommunicate/Classes/Views/CustomPreChatFormView.swift
- Updated KM Chat UI to 0.2.0 which will add KM Core 1.0.1
> Update to KM Chat UI 0.2.0

- CHANGELOG.md
- MIGRATING.md
- Sources/Kommunicate/Classes/KMConversationService.swift
- Sources/Kommunicate/Classes/Kommunicate.swift
- Moved Conversation metadata, assignee, teamid updated to a separate function
- Deprecated `Kommunicate.UpdateTeamId()` method & make it to use this method 
```
Use this method to update assignee or teamId & metadata. Don't try to update assignee & teamId at the same time.
let conversationId = "your_conversation_id"
let assigneeId = "your_assignee_id"
let metaData = ["key1":"value1", "key2": "key2", "key3":"value3"]
```
If you want to update conversation assignee, then create conversation object like this:
``` 
let conversation = KMConversationBuilder().withClientConversationId(conversationId).withConversationAssignee(assigneeId).build()
```
If you want to update teamId & conversation meta data, then create conversation object like this:
``` 
let conversation = …
```
> [CM-666] Move conversation metadata and assignee update to a separate function 

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
> updated KM Chat UI to 0.2.4

- CHANGELOG.md
- Example/Podfile
- Example/Podfile.lock
- Sources/Kommunicate/Classes/KMConversationViewController.swift
- Added Text To Speech (TTS) for message
- Added a setting to enable/disable the TTS. By default it is disabled
> [CM-1015] Text To Speech Feature

- CHANGELOG.md
- Example/Podfile
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Upgraded KommunicateChatUI-iOS-SDK to 0.2.5
> upgraded KM-ChatUI to 0.2.5

- CHANGELOG.md
- Example/Kommunicate/AppDelegate.swift
- Sources/Kommunicate/Classes/KMPushNotificationHandler.swift
- Clicking Notification Does not conversation when app is not running. 
https://user-images.githubusercontent.com/61688116/186605921-ce47877c-eaa7-445d-b9f2-82554c204e92.MP4
https://user-images.githubusercontent.com/61688116/186605908-9adcacde-f3d1-4cf8-ae84-9039c493b737.MP4
> [CM-1020] Clicking Notification Does not open conversation

- CHANGELOG.md
- Example/Podfile
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Upgraded KM Chat UI to 0.2.6
- updated podfile & changelog
> Upgraed KM Chat UI to 0.2.6

- CHANGELOG.md
- Sources/Kommunicate/Classes/Kommunicate.swift
- If we share the location, preview is not showing. And also api key was older & updated it
> [CM-1146] Fixed Location Preview issue

- CHANGELOG.md
- Example/Kommunicate.xcodeproj/project.pbxproj
- Example/Podfile
- Example/Podfile.lock
- Sources/Kommunicate/Classes/KMAppSettingsResponse.swift
- Sources/Kommunicate/Classes/KMConversationListViewController.swift
- Sources/Kommunicate/Classes/KMConversationService.swift
- Sources/Kommunicate/Classes/Kommunicate.swift
-  Identifying zendesk user & storing the account key for initialisation
- Updating source of the conversation for zendesk users (To restrict sending messages from Kommunicate dashboard)
- Created new flow for opening the Zendesk conversation
> [CM-1189] Added zendesk integration to the sdk

- CHANGELOG.md
- Example/Podfile
- Example/Podfile.lock
- Sources/Kommunicate/Classes/Kommunicate.swift
- Added authentication flow for zendesk users
- Updated opening zendesk chat flow to maintain chat session
> [CM-1217] Zendesk Authentication flow for user

- CHANGELOG.md
- Sources/Kommunicate/Classes/Kommunicate.swift
- Added function to close the Conversation screen
> [CM-1227] Added Support to close the chat widget

- CHANGELOG.md
- Example/Podfile
- Example/Podfile.lock
- Sources/Kommunicate/Classes/FaqViewController.swift
- Sources/Kommunicate/Classes/KMConversationViewController.swift
- Sources/Kommunicate/Classes/KMPushNotificationHelper.swift
- Sources/Kommunicate/Classes/Kommunicate.swift
- Sources/Kommunicate/Classes/Views/ConversationClosedView.swift
- Sources/Kommunicate/Classes/Views/FeedbackRatingView.swift
- Improved Events to get call back for chat widget events
- created callbacks for each event with defined parameters
> [CM-1265] Improve Events & Expose message to the events

- CHANGELOG.md
- Example/Podfile
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- upgraded KM Chat UI to 0.2.8
> upgraded chat ui to 0.2.8

- CHANGELOG.md
- Example/Kommunicate.xcodeproj/project.pbxproj
- Example/Podfile
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Sources/Kommunicate/Classes/FaqViewController.swift
- Sources/Kommunicate/Classes/KMAppSettingsResponse.swift
- Sources/Kommunicate/Classes/KMConversationListViewController.swift
- Sources/Kommunicate/Classes/KMConversationService.swift
- Sources/Kommunicate/Classes/KMConversationViewController.swift
- Sources/Kommunicate/Classes/KMPushNotificationHelper.swift
- Sources/Kommunicate/Classes/Kommunicate.swift
- Sources/Kommunicate/Classes/Views/ConversationClosedView.swift
- Sources/Kommunicate/Classes/Views/FeedbackRatingView.swift
- Added Support Zendesk Integration
- Improved Event callback
> release_6.7.5

- CHANGELOG.md
- Example/Kommunicate/Base.lproj/Localizable.strings
- Example/Podfile
- Example/Podfile.lock
- Sources/Kommunicate/Classes/KMConversationListViewController.swift
- Added Start new conversation button at the bottom of the Conversation List Screen
- Added localisation, visibility customization
- This change  is to match with android sdk
> [CM-1280] Added Start New Conversation Button

- CHANGELOG.md
- Example/Podfile
- Example/Podfile.lock
- Sources/Kommunicate/Classes/Kommunicate.swift
- Added function to unsubscribe chat events
```
Kommunicate.unsubcribeCustomEvents()
```
> Added Support for Unsubscribe events

- CHANGELOG.md
- Example/Podfile
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Upgraded KM Chat UI to 0.2.9
- Update Changelog
> upgraded KM Chat ui to 0.2.9

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
> upgraded sdk version

- Example/Podfile
- Example/Podfile.lock
- Sources/Kommunicate/Classes/CustomPreChatFormViewController.swift
- Sources/Kommunicate/Classes/Extensions/UIViewController+Extension.swift
- Added Support for App-extensions
- Calling UIApplication.shared directly is not supported in App extensions. Added UIApplication+Extension file
> [CM-1180] Added support for app extensions

- CHANGELOG.md
- Example/Podfile
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Upgraded KM Chat UI to 0.3.0
> Updated KM Chat ui to 0.3.0

- Sources/Kommunicate/Classes/FaqViewController.swift
- Disabled zoom in / out on FAQView Controller to give native user experience
> [CM-1303] Disabled Zoom in/out on Webview

- Example/Podfile
- Example/Podfile.lock
- Sources/Kommunicate/Classes/KMConversationViewController.swift
- Added support for giving feedback for conversation when bot handling the conversation.
- Now user can give rating whenever they want similar to web
> [CM-1278] Added support for giving feedback for the conversation anytime

- Sources/Resources/Assets/Localizable.strings
- Added default text for conversation View Controller Text
> Added default text for Conversationvctitle 

- Example/Podfile
- Example/Podfile.lock
- Sources/Kommunicate/Classes/Utilities/KmConfigurationSetter.swift
- Added support for setting restartConversationButton, rateConversation, backButton on conversationalist screen, hideBottom start Conversation button from json string
- tested by passing json string with possible values
> Added customisation from string for restart conversation

- CHANGELOG.md
- Example/Podfile
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Fixed attempt to insert section 1 but there are only 1 sections after the update crash
- Added Support for rating button on conversation screen
- Added Support for metadata for form action messages
> Updated km chat ui to 0.3.1

- CHANGELOG.md
- Sources/Kommunicate/Classes/Kommunicate.swift
- Added Support for auto logout when new different user is trying to register when another user is already logged in
- Fixed setting client channel key based on single thread configuration from dashboard
> [CM-1340] Fixed  Auto logout and Channel client key

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Sources/Kommunicate/Classes/Kommunicate.swift
- updated pod version to 6.8.0
- updated changelog
> Upgraded Pod version

- Sources/Kommunicate/Classes/KMPushNotificationHelper.swift
- Sources/Kommunicate/Classes/Kommunicate.swift
- updated function names on Notification Helper class
> [CM-1203] Updated Notification Helper Class

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Sources/Kommunicate/Classes/Kommunicate.swift
- Upgraded KM Chat UI to 1.0.0
> Upgraded KM Chat UI to 1.0.0

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Sources/Kommunicate/Classes/Kommunicate.swift
- Upgraded pod version to 6.8.3
- Updated Chagelog
> Upgraded Pod version to 6.8.3

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Sources/Kommunicate/Classes/Kommunicate.swift
- Upgraded KM Chat UI to 1.0.2
- updated pod version to 6.8.4
- Updated chagnelog
> Upgraded KM Chat UI to 1.0.2

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Sources/Kommunicate/Classes/Kommunicate.swift
- Updated KM Chat UI to 1.0.3
- Updated Changelog
> Upgrade 6.8.5

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Sources/Kommunicate/Classes/Kommunicate.swift
- Updated KM Chat UI to 1.0.4
- Updated changelog
> Upgraded pod version to 6.8.6

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Sources/Kommunicate/Classes/Kommunicate.swift
- Updated KM Chat UI to 1.0.5
- Updated Kingfisher to 7.6.2
> Upgrade chatui to 1.0.5

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Fixed down arrow coming in bottom of the screen when welcome message get rendered issue.
- Form Submit button width is corrected.
- Added border to the form and removed paddding form the top of each cell.
> upgraded chat ui to 1.1.3

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Improved UI of multiple language selection & make it similar to android
- Refresh Icon Change
> upgrade chatui

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Fixed keyboard overlapping in Rating Screen.
- Fixed Away Message & Rating message overlapping
- Bug Fixes
> Upgraded ChatUI to 1.1.5

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Fixed attachments upload issue
> upgraded chat ui to 1.1.6

- Sources/Kommunicate/Classes/Models/ChatMessage.swift
- Added instance of platformSource.
> [CM-1510] Add icons on conversation list screen

- Example/Kommunicate.xcodeproj/project.pbxproj
- Example/Podfile
- Example/Podfile.lock
- Kommunicate.podspec
- Package.swift
> Updated min version to 13

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
> Upgraded PodFile to 7.0.2

- Sources/Kommunicate/Classes/Extensions/URLBuilder+Settings.swift
- Sources/Kommunicate/Classes/KMAppSettingsResponse.swift
- Sources/Kommunicate/Classes/KMConversationService.swift
- Sources/Kommunicate/Classes/Kommunicate.swift
- Upgraded appsettings api to V3
- Optimised create conversation flow
- Created a function to refresh the appsetttings
- As a result of above three , Able to reduce the create conversation flow
> [CM-1676] Upgraded Appsetttings api & optimised the create conversation flow

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Fixed Button spacing
- Upgraded appsetttings api & optimised the create conversation flow
> Upgraded PodFile to 7.0.3

- Sources/Kommunicate/Classes/Kommunicate.swift
- Fixed the single thread issue
> fixed single thread

- Sources/Kommunicate/Classes/KMConversationListViewController.swift
- Fix for random conversation opening failure
> Fix for random conversation opening failure

- Sources/Kommunicate/Classes/Kommunicate.swift
- Reverted the Changes made in createConversation and createAndShowConversation
> Fix createAndShowConversation bug

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Fixed createAndShowConversation bug
> Upgraded PodFile to 7.0.6

- Sources/Kommunicate/Classes/FaqViewController.swift
- Sources/Kommunicate/Classes/Views/ConversationClosedView.swift
- Created a dynamic Style to pass in webView to get a feel of dark Mode. 
https://github.com/Kommunicate-io/Kommunicate-iOS-SDK/assets/139110221/8a581fca-b8a9-47cd-858f-5cd0fc37e17e
> [CM-1660] Dark Mode Support Part - 3 (Dynamic Change)

- Sources/Kommunicate/Classes/KMConversationViewController.swift
- Added New Typing indicator.
- Added the typing indicator for bot delay.
> [CM-1374] Typing Indicator 

- Sources/Kommunicate/Classes/KMConversationViewController.swift
- Added support for event callback for resolve event
- Tested for normal conversation resolve event
- Tested for Zendesk Conversation resolve event from by ending the chat from zendesk dashboard
> Re Added support Resolve event callback

- Sources/Kommunicate/Classes/Kommunicate.swift
- Removed "KM_ASSIGN" from hiddenMessage Restriction
> [CM-1853] Assign To message UI Match, Message text 

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Upgraded Pod version to 7.1.3
- Upgraded KM chat UI to 1.2.8
- Updated Changelog
> Upgraded chat ui to 1.2.8

- Sources/Kommunicate/Classes/Extensions/UIViewController+Extension.swift
- Sources/Kommunicate/Classes/KMConversationViewController.swift
- Added a check to verify the Current Screen Before showing the Rating Bar.
> [CM-1977] Improve the Flow of Showing Rating Bar

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Updated the Chat UI to 1.3.0
> Updated podFile for ChatUI to 1.3.0

- Sources/Kommunicate/Classes/FaqViewController.swift
- Sources/Kommunicate/Classes/KMConversationListViewController.swift
- Sources/Kommunicate/Classes/KMConversationViewController.swift
- Sources/Kommunicate/Classes/Kommunicate.swift
- Added prefix for the file names to avoid compilation issue
- Tested the SDK after the changes
> [CM-1949] Added prefix for the file names to avoid compilation issue

- Sources/Kommunicate/Classes/Models/ChatMessage.swift
- Added a dependency of assignedTags in ALKChatViewModelProtocol
> [CM-824] Show tags on conversation list same as that on dashboard | iOS Agent App

- Sources/Kommunicate/Classes/Extensions/NotificationCenter+Extension.swift
- Sources/Kommunicate/Classes/KMConversationListViewController.swift
- Added support for conversation deletion(from dashboard) sync
> [CM-1627] Added support for conversation deletion when chat screen is not on top

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Updated Change Log.
- Updated the pod KM Chat UI to 1.3.1
- Updated the pod KM iOS SDK to 7.1.7
> Updated podFile to 7.1.7

- Sources/Kommunicate/Classes/KMAppSettingsService.swift
- Removed setting of CSATBaseRatting. As already given default value to it.
> Fixed Sent Message Colour issue

- Sources/Kommunicate/Classes/Kommunicate.swift
> [CM-2178] Google API keys leakage | iOS SDK

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
> Updated podfile to 7.2.0

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
> Updated Podfile to 7.2.1

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Supports Xcode version 15.5 and above.
- Fixed the issue of placeholder in Autosuggestion while bot delay.
> Release 7.2.1

- Example/Kommunicate.xcodeproj/project.pbxproj
- Example/Kommunicate_ExampleUITests/KommunicateCreateConversationAndSendMessagesTests.swift
- Example/Kommunicate_ExampleUITests/KommunicateFormRichMessageUITests.swift
- Example/Kommunicate_ExampleUITests/KommunicateLoginAsVisitorUITests.swift
- Example/Kommunicate_ExampleUITests/KommunicateRichMessageUITests.swift
- Example/Kommunicate_ExampleUITests/TestCaseInfo.swift
- Example/Tests/ConversationVCNavBarSnapshotTests.swift
- Example/Tests/KMConversationViewControllerTests.swift
- Example/Tests/MessageMetadataTests.swift
- Updated the automation testing code. 
- Updated the testing minimum simulator version to 13.
- Update the value of `loginCreadentials` in `TestCaseInfo`.
> [CM-2193] Run old automation - Fix if any dependency

- Example/Kommunicate_ExampleUITests/KommunicateRichMessageUITests.swift
- Example/Kommunicate_ExampleUITests/TestCaseInfo.swift
- Added Automation in Rich Message Testing.
- Automated -  `Video Rich Message`, `Auto Suggestion`, `Custom Input Field`, `Youtube Video Rich Message` and `HTML Rich  Message`
> [CM-2219] Automation in Rich message | iOS SDK

- CHANGELOG.md
- Example/Kommunicate.xcodeproj/project.pbxproj
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Fixed Away Message not showing in Bot Delay.
- Fixed an issue where captions were cut off in Video Rich Messages.
- Made the Zendesk Plugin optional for integration flexibility.
- Added a new feature to collect email addresses in Away Mode.
> Updated podfile to 7.2.4

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Updated ChatUI version to 1.3.9
- Updated SDK Version to 7.2.5
> Updated Pod Version to 7.2.5

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
- Added Waiting Queue UI and related functions.
- Synchronized Default configuration for Swift 6 support.
- AWS-ENCRYPTED- prefix removed from attachment upload in Conversation Screen.
- Fixed Restart Button not working.
> Updated Pod Version to 7.2.6

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
> Updated PodFile to 7.2.8

- .github/workflows/ios-automation-test.yaml
- Example/Kommunicate/AppDelegate.swift
- Example/Kommunicate_ExampleUITests/KommunicateResolveAndAssignmentUITests.swift
- Example/Tests/KommunicateTests.swift
- Example/Tests/PaymentTests.swift
- Sources/Kommunicate/Classes/ConversationDetail.swift
- Sources/Kommunicate/Classes/Extensions/UIButton+Extension.swift
- Sources/Kommunicate/Classes/KMConversationListViewController.swift
- Sources/Kommunicate/Classes/KMConversationService.swift
- Sources/Kommunicate/Classes/KMConversationViewController.swift
- Sources/Kommunicate/Classes/Kommunicate.swift
- Sources/Kommunicate/Classes/Models/KMMessageBuilder.swift
- Sources/Kommunicate/Classes/PricingPlan.swift
- Sources/Kommunicate/Classes/URLBuilder.swift
- Sources/Kommunicate/Classes/Utilities/KMBusinessHourUtilities.swift
- Merging all the changes related to [CM-2362] [CM-2363] [CM-2359] for Applozic to Kommunicate:  iOS SDK Transformation 
KM_ChatUI_Branch : `remove-applozic-references`
KM_Core_Branch: `remove-applozic-references`
[CM-2362]: https://kommunicate.atlassian.net/browse/CM-2362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CM-2363]: https://kommunicate.atlassian.net/browse/CM-2363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CM-2359]: https://kommunicate.atlassian.net/browse/CM-2359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CM-2362] [CM-2363] [CM-2359] Applozic to Kommunicate:  iOS SDK Transformation 

- Sources/Kommunicate/Classes/Kommunicate.swift
- Executing the code to clear cache.
KM_ChatUI_Branch : `CM-2395`
> [CM-2395] Form Data Persist in Local Cache| iOS SDK

- CHANGELOG.md
- Example/Podfile.lock
- Kommunicate.podspec
- Package.resolved
- Package.swift
> Updated Podfile to 7.3.0
